version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZabbixSQL
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
    command: --log-bin-trust-function-creators=1 --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - zabbix_db:/var/lib/mysql
    networks:
      - zabbixnet

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0.2
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
    depends_on:
      - mysql
    networks:
      - zabbixnet

  zabbix-frontend:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.0.2
    container_name: zabbix-frontend
    restart: always
    ports:
      - "8080:8080" 
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix123
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbixnet

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0.2
    container_name: zabbix-agent
    restart: always
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      zabbixnet:    
        ipv4_address: 172.18.0.6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000" 
    volumes:
      - grafana_db:/var/lib/grafana
    networks:
      - zabbixnet

volumes:
  zabbix_db:
  grafana_db:

networks:
  zabbixnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

